CUDA_VISIBLE_DEVICES=0,1,2,5 \
NPROC_PER_NODE=4 \
swift rlhf \
    --rlhf_type grpo \
    --model_type qwen2_5 \
    --model models/QwenQwen2.5-Coder-7B-Instruct \
    --external_plugins tools/plugin.py \
    --reward_funcs external_countdown \
    --use_vllm true \
    --vllm_max_model_len 8192 \
    --vllm_tensor_parallel_size 2 \
    --vllm_gpu_memory_utilization 0.7 \
    --vllm_enforce_eager true \
    --train_type full \
    --torch_dtype bfloat16 \
    --custom_register_path tools/dataset_pre.py \
    --dataset datasets/prompt003.jsonl \
    --max_length 4096 \
    --max_completion_length 4096 \
    --num_train_epochs 10 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --learning_rate 5e-7 \
    --gradient_accumulation_steps 1 \
    --eval_steps 500 \
    --save_steps 100 \
    --save_total_limit 2 \
    --logging_steps 1 \
    --warmup_ratio 0.01 \
    --dataloader_num_workers 4 \
    --num_generations 4 \
    --temperature 1.0 \
    --deepspeed zero3 \
    --log_completions true \
    --beta 0.001 \
    --num_iterations 1